### ISSUE TITLE
bug: `outputPath` config seems doesn't work

### ISSUE THREAD

**Issue by hustcer** [innocces/dumi-theme-chakra#14]
### 版本

- dumi-theme-chakra: current latest  —— v0.0.11
- dumi: v2.1.13
- node: v16.16.0
- npm: v8.11.0
- OS: macOS 13.2.1 
- Browser: Edge latest

### 复现步骤

1. git clone https://github.com/innocces/dumi-theme-chakra.git
2. Add `outputPath: 'dist-doc',` config to `example/.dumirc.ts`, for more detail: https://d.umijs.org/config#outputpath
3. Run `pnpm run build`

### 你期望的现象？

The static assets should output to `dist-doc` directory

### 现有的现象？

The static assets actually output to `dist` directory
可能还有其他的 dumi 官方支持的配置项在该主题里面不被支持？麻烦检查一下，谢谢哈

### 复现 repo(最好可以提供一个复现的 repo)

https://github.com/innocces/dumi-theme-chakra.git

**Comment by hustcer** [comment]
Any update on this? Or do I use it  in the wrong way? Thanks

**Comment by innocces** [comment]
> Any update on this? Or do I use it in the wrong way? Thanks

working~ will be check delay

**Comment by hustcer** [comment]
可以复现么？

**Comment by innocces** [comment]
> 可以复现么？

感觉你说配置不生效是因为我是用pnpm做管理器的。dumi2在pnpm的模式下解析依赖很慢. 我在注释apiParser之后打包是正常的. 

<img width="314" alt="image" src="https://user-images.githubusercontent.com/38065966/224650381-247c1016-b647-4a05-8d57-eb04ace2dbaa.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/38065966/224650499-e8405786-c4c0-4460-bd51-3594ded9eb3d.png">

**Comment by hustcer** [comment]
> 感觉你说配置不生效是因为我是用pnpm做管理器的。dumi2在pnpm的模式下解析依赖很慢. 我在注释apiParser之后打包是正常的.

这个结论在这个例子里面确实是成立的，但是我自己创建了个文档仓库在没有配置 `apiParser` 和 `resolve` 的情况下也是无效的，有点诡异啊

**Comment by hustcer** [comment]
可以看下这个 demo： https://github.com/hustcer/dumi-demo/tree/master 可以复现我说的问题

**Comment by innocces** [comment]
> 可以看下这个 demo： https://github.com/hustcer/dumi-demo/tree/master 可以复现我说的问题

![image](https://user-images.githubusercontent.com/38065966/224662320-a84a6e40-2a77-48d4-b436-b6e34cc877b6.png)
怎么是mts. 应该是ts

**Comment by hustcer** [comment]
如果是 ts 的话会有这个报错：
```console
info  - dumi v2.1.15
fatal - Error: Parse config file failed: [/Users/hustcer/github/terminus/dumi-demo/.dumirc.ts]
    at Function.getUserConfig (/Users/hustcer/github/terminus/dumi-demo/node_modules/@umijs/core/dist/config/config.js:161:17)
    at Config.getUserConfig (/Users/hustcer/github/terminus/dumi-demo/node_modules/@umijs/core/dist/config/config.js:58:19)
    at DumiService.run (/Users/hustcer/github/terminus/dumi-demo/node_modules/@umijs/core/dist/service/service.js:233:37)
    at DumiService.run2 (/Users/hustcer/github/terminus/dumi-demo/node_modules/umi/dist/service/service.js:65:23)
    at /Users/hustcer/github/terminus/dumi-demo/node_modules/dumi/dist/service/forkedDev.js:24:19
    at Object.<anonymous> (/Users/hustcer/github/terminus/dumi-demo/node_modules/dumi/dist/service/forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  [cause]: /Users/hustcer/github/terminus/dumi-demo/node_modules/dumi-theme-chakra/dist/factory/defineThemeConfig.js:6
  export default function defineThemeConfig(config) {
  ^^^^^^

  SyntaxError: Unexpected token 'export'
      at Object.compileFunction (node:vm:352:18)
      at wrapSafe (node:internal/modules/cjs/loader:1033:15)
      at Module._compile (node:internal/modules/cjs/loader:1069:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Object.newLoader [as .js] (/Users/hustcer/github/terminus/dumi-demo/node_modules/@umijs/utils/compiled/pirates/index.js:1:1684)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (/Users/hustcer/github/terminus/dumi-demo/.dumirc.ts:34:40)
}
fatal - A complete log of this run can be found in:
fatal - /Users/hustcer/github/terminus/dumi-demo/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
```

**Comment by innocces** [comment]
> https://github.com/hustcer/dumi-demo/tree/master

https://github.com/hustcer/dumi-demo/blob/1599ca189925d512e1b53dd909108bdc86c8fccb/.dumirc.mts#L2

暂时不要用这个了。导出方式不太对。

**Comment by hustcer** [comment]
> > https://github.com/hustcer/dumi-demo/tree/master
> 
> https://github.com/hustcer/dumi-demo/blob/1599ca189925d512e1b53dd909108bdc86c8fccb/.dumirc.mts#L2
> 
> 暂时不要用这个了。导出方式不太对。

那正确的使用姿势是什么样的呢?

**Comment by innocces** [comment]
先暂时直接参考文档写配置吧。这个define的函数还要再修改

```ts
export default defineConfig({
  themeConfig: {}
})
```

**Comment by hustcer** [comment]
OK, 谢谢

**Comment by innocces** [comment]
那先关掉了

**Comment by hustcer** [comment]
> 这个define的函数还要再修改

那这个你还会改好发版的么？大概什么时候？

**Comment by innocces** [comment]
最近很忙暂时没有时间弄了。如果有兴趣可以参与弄一下

**Comment by innocces** [comment]
> > 这个define的函数还要再修改
> 
> 那这个你还会改好发版的么？大概什么时候？

https://github.com/innocces/dumi-theme-chakra/releases/tag/v0.0.15

已经可用了。你可以参考新的readme使用
